export const CurrencyArray = [
  { currency: "USD", symbol: "$", name: "United States Dollar" },
  { currency: "EUR", symbol: "€ ", name: "Euro" },
  { currency: "ETH", symbol: "Ξ", name: "Ethereum" },
  { currency: "BTC", symbol: "₿", name: "Bitcoin" },
  { currency: "LTC", symbol: "Ł", name: "Litecoin" },
  { currency: "BCH", symbol: "B", name: "Bitcoin Cash" },
  { currency: "BNB", symbol: "B", name: "Binance Coin" },
  { currency: "XRP", symbol: "XRP", name: "Ripple" },
  { currency: "XLM", symbol: "XLM", name: "Stellar Lumens" },
  { currency: "AED", symbol: "د.إ	", name: "Emirati Dirham" },
  { currency: "NGN", symbol: "₦", name: "Nigerian Naira" },
  { currency: "ZAR", symbol: "R", name: "South African Rand" },
  { currency: "BRL", symbol: "R$", name: "Brazilian Real" },
  { currency: "CHF", symbol: "CHF", name: "Swiss Franc" },
  { currency: "JPY", symbol: "¥", name: "Japanese Yen" },
  { currency: "CAD", symbol: "CA$", name: "Canadian Dollar" },
  { currency: "AUD", symbol: "AU$", name: "Australian Dollar" },
  { currency: "GBP", symbol: "£", name: "Pound Sterling" },
  { currency: "CNY", symbol: "¥", name: "Chinese Yuan Renminbi" },
  { currency: "MXN", symbol: "$", name: "Mexican Peso" },
  { currency: "HKD", symbol: "HK$", name: "Hong Kong Dollar" },
  { Currency: "SGD", symbol: "S$", name: "Singapore Dollar" },
];
