import type { Metadata } from "next";
import "./globals.css";
import Navigation from "../components/Navigation";
import CryptoProvider from "./Providers/CryptoProvider";
import { PortFolioProvider } from "./Providers/PortfolioProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <CryptoProvider>
          <PortFolioProvider>
            <Navigation />
            {children}
          </PortFolioProvider>
        </CryptoProvider>
      </body>
    </html>
  );
}
