

import type { Metadata } from "next";
import "./globals.css";
import Providers from "./Providers/CryptoProvider";
import {store} from './store'
import { Provider } from 'react-redux'
import Navigation from "../components/Navigation";
import CryptoProvider from "./Providers/CryptoProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
        <CryptoProvider>
          <Navigation />
          {children}
        </CryptoProvider>
        </Provider>
      </body>
    </html>
  );
}
