import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./components/Navigation";
import CryptoProvider from "./Providers/CryptoProvider";
import StoreProvider from "./Providers/StoreProvider";
import { PortFolioProvider } from "./Providers/PortfolioProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <CryptoProvider>
            <Navigation />
            {children}
          </CryptoProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
